name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  http: ^1.4.0
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  like_button: ^2.1.0
  liquid_pull_to_refresh: ^3.0.1
  provider: ^6.1.5
  supabase_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/icons/icon_blynd_light.png
  - assets/icons/icon_blynd_dark.png
  - assets/preview/BLYND Feed.jpg
  - assets/preview/BLYND Settings.jpg
  - assets/preview/BLYND Profile.jpg
  - assets/preview/Blynd.png
