name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  supabase_flutter: ^2.3.4
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  package_info_plus: ^4.2.0
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  flutter_animate: ^4.5.2
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.1.0
  iconsax: ^0.0.8
  like_button: ^2.1.0
  liquid_pull_to_refresh: ^3.0.1
  provider: ^6.1.1
  timeago: ^3.6.1
  url_launcher: ^6.2.4
  file_picker: ^10.1.9
  video_player: ^2.10.0
  chewie: ^1.7.5
  flutter_cache_manager: ^3.4.1
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/icons/icon_blynd_light.png
  - assets/icons/icon_blynd_dark.png
  - assets/preview/BLYND Feed.jpg
  - assets/preview/BLYND Settings.jpg
  - assets/preview/BLYND Profile.jpg
  - assets/preview/Blynd.png
